#name: Run unit tests
#
#on:
#  pull_request:
#  push:
#    branches:
#      - "develop"
#      - "main"
#
#concurrency:
#  group: ${{ github.ref }}-${{ github.workflow }}
#  cancel-in-progress: true
#
#permissions: read-all
#
#jobs:
#  unit-tests:
#    runs-on: ubuntu-20.04
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#
#      - name: Prepare Android Environment
#        uses: ./.github/actions/prepare-android-env
#
#      - name: Run test
#        run: ./gradlew testDebugUnitTest
#        env:
#          GITHUB_USER: ${{ github.actor }}
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Include Slack Notification
#        if: failure() && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master')
#        uses: ./.github/actions/slack-notification
#        env:
#          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
#          SLACK_GIT_REF: ${{ github.ref }}
#          SLACK_WORKFLOW: ${{ github.workflow }}
