name: Run unit tests

on:
  pull_request:
  push:
    branches:
      - "develop"
      - "main"

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions: read-all

jobs:
  unit-tests:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Unit Test with Android Emulator Runner
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck

        env:
          GITHUB_USER: ${{ github.actor }}

      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: app/build/reports/coverage/androidTest/debug

      - name: Include Slack Notification
        if: failure() && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master')
        uses: ./.github/actions/slack-notification
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_GIT_REF: ${{ github.ref }}
          SLACK_WORKFLOW: ${{ github.workflow }}