name: "Run unit tests"

on:
  pull_request:
  push:
    branches:
      - "develop"
      - "main"

permissions: read-all

jobs:
  unit-tests:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare Android Environment
        uses: ./.github/actions/prepare-android-env

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: Run test
        run: ./gradlew testDebugUnitTest
        env:
          GITHUB_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
