name: Tests

on:
  pull_request:
  push:
    branches:
      - "develop"
      - "main"

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-20.04
    permissions:
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@v1.2.3
        with:
          name: "app/google-services.json"
          json: ${{ secrets.GOOGLE_SERVICES_JSON }}

      - name: Add google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo "$GOOGLE_SERVICES_JSON" | base64 --decode > app/google-services.json

      - name: Prepare Android Environment
        uses: ./.github/actions/prepare-android-env

      - name: Run test
        run: ./gradlew testDebugUnitTest
        env:
          LOUDIUS_CLIENT_SECRET: ${{ secrets.LOUDIUS_CLIENT_SECRET }}
          LOUDIUS_CLIENT_ID: ${{ secrets.LOUDIUS_CLIENT_ID }}
          LOUDIUS_GITHUB_USER_PASSWORD: ${{ secrets.LOUDIUS_GITHUB_USER_PASSWORD }}
          LOUDIUS_GITHUB_USER_NAME: ${{ secrets.LOUDIUS_GITHUB_USER_NAME }}
          LOUDIUS_GITHUB_USER_OTP_SECRET: ${{ secrets.LOUDIUS_GITHUB_USER_OTP_SECRET }}

      - name: Upload tests results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-unit
          path: |
            */build/test-results/**
            */build/paparazzi/failures/**
            */build/outputs/**
            */build/tmp/kotlin-classes/**
          retention-days: 5

  code-coverage:
    name: Merged code coverage
    runs-on: ubuntu-20.04
    permissions:
      pull-requests: write
    needs:
      - unit-tests

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare Android Environment
        uses: ./.github/actions/prepare-android-env

      - name: Download tests results for both jobs
        uses: actions/download-artifact@v4
        with:
          name: test-results-unit

      - name: Run code coverage
        run: ./gradlew codeCoverage

      - name: Store HTML coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: |
            */build/reports/jacoco/codeCoverage

      - name: Add coverage to PR
        if: ${{ github.event_name != 'schedule' }}
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: |
            */build/reports/jacoco/codeCoverage/codeCoverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
