name: Run unit tests

on:
  pull_request:
  push:
    branches:
      - "develop"
      - "main"

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  unit-tests:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare Android Environment
        uses: ./.github/actions/prepare-android-env

      - name: Run test
        run: ./gradlew test

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure() # run this step even if previous step failed
        with:
          name: Tests Results
          path: "*/build/test-results/**/*.xml"
          reporter: java-junit

      - name: Upload failed tests results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: failed-tests-results
          path: |
            */build/reports/**

      - name: Include Slack Notification
        if: failure() && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master')
        uses: ./.github/actions/slack-notification
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_GIT_REF: ${{ github.ref }}
          SLACK_WORKFLOW: ${{ github.workflow }}
