name: Android Release

on:
  pull_request:
  push:
    branches:
      - "develop"
      - "main"
  schedule:
    # Run twice a day the sanity check, at 9:13 and 21:13.
    # You ask why 13? because probably less people schedule their tasks at exactly this time, so I
    # guess CI is less occupied. And 13 is a lucky number ;)
    - cron: "13 9,21 * * *"

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions: read-all

jobs:
  apk:
    name: Run UI tests on Firebase Test Lab
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "build-tools/requirements.txt"

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Download test matrix ID artifact
        if: github.ref == 'refs/heads/your-branch-name'
        uses: actions/download-artifact@v2
        with:
          name: test-matrix-id

      - name: Set testMatrixId output
        id: previous_test_matrix
        if: github.ref == ${{ github.ref}} && steps.download.outputs.artifacts_downloaded == 'true'
        run: echo "::set-output name=testMatrixId::$(cat test_matrix_id.txt)"

      - name: Cancel previous test run on Firebase Test Lab
        if: steps.previous_test_matrix.outputs.testMatrixId != ''
        run: |
          gcloud firebase test android matrices cancel ${{ steps.previous_test_matrix.outputs.testMatrixId }}

      - name: Prepare Android Environment
        uses: ./.github/actions/prepare-android-env

      - name: Assemble App Debug APK and Android Instrumentation Tests
        run: ./gradlew assembleDebug assembleDebugAndroidTest

      - name: Check APK file existence
        run: |
          if [ -f app/build/outputs/apk/debug/app-debug.apk ]; then
            echo "APK file exists."
          else
            echo "APK file does not exist."
            exit 1
          fi

      - name: Check APK file permissions
        run: |
          if [ -r app/build/outputs/apk/debug/app-debug.apk ]; then
            echo "APK file has read permissions."
          else
            echo "APK file does not have read permissions."
            exit 1
          fi

      - name: Upload APK to GCS
        run: |
          gsutil cp app/build/outputs/apk/debug/app-debug.apk gs://${{ steps.generate-dir.outputs.bucket }}/app-debug.apk
          gsutil cp app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk gs://${{ steps.generate-dir.outputs.bucket }}/app-debug-androidTest.apk


      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          install_components: "gsutil"

      - id: generate-dir
        name: Generate random directory
        run: |-
          echo "results_dir=$(date +%F_%T)-${RANDOM}" >> "$GITHUB_OUTPUT"
          echo "bucket=test-lab-07qs3ns6c51bi-iazpthysivhkq" >> "$GITHUB_OUTPUT"


      - name: Create Firebase Test Lab Matrix
        id: tests
        run: |
          requestBody='{
            "environmentMatrix": {
              "androidDeviceList": {
                "androidDevices": [
                  {
                    "androidModelId": "Pixel2",
                    "androidVersionId": "30",
                    "locale": "en",
                    "orientation": "portrait"
                  }
                ]
              }
            },
            "testSpecification": {
              "androidInstrumentationTest": {
                "testApk": {
                  "gcsPath": gs://${{ steps.generate-dir.outputs.bucket }}/app-debug-androidTest.apk
                },
                "appPackageId": "com.appunite.loudius",
                "appApk": {
                  "gcsPath": gs://${{ steps.generate-dir.outputs.bucket }}/app-debug.apk
                }
              }
            },
            "resultStorage": {
              "googleCloudStorage": {
                "gcsPath": "gs://${{ steps.generate-dir.outputs.bucket }}/${{ steps.generate-dir.outputs.results_dir }}"
              }
            }
          }'
          
          responseBody=$(curl -X POST \
          -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" \
          -H "Content-Type: application/json" \
          -d "$requestBody" \
          "https://testing.googleapis.com/v1/projects/${{ secrets.FIREBASE_PROJECT_ID }}/testMatrices")

          echo "Test Matrix response body: $responseBody"
          test_matrix_id=$(echo "$responseBody" | jq -r '.testMatrixId')
          
          echo "Test Matrix ID: $test_matrix_id"
          echo $test_matrix_id > test_matrix_id.txt
          echo "::set-output name=testMatrixId::$test_matrix_id"

      - name: Upload test matrix ID artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-matrix-id
          path: test_matrix_id.txt

      - name: Check for the test status
        run: |
          responseBody=$(curl -X GET \
          -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" \
          -H "Content-Type: application/json" \
          "https://testing.googleapis.com/v1/projects/${{ secrets.FIREBASE_PROJECT_ID }}/testMatrices/${{steps.tests.outputs.testMatrixId}}"/)
          
          echo "Test Matrix response body from get: $responseBody"


      - name: Upload to Big Query
        if: always()
        run: |-
          mkdir "build/test-results"
          gsutil cp -r "gs://${{ steps.generate-dir.outputs.bucket }}/${{ steps.generate-dir.outputs.results_dir }}/Pixel2-30-en-portrait/test_result_1.xml" "build/test-results/results.xml"
          if [[ "${{ github.event_name }}" != "pull_request" ]]; then
            python "build-tools/upload-junit-to-cloud.py" --final
          else
            python "build-tools/upload-junit-to-cloud.py"
          fi

      - name: Check for the test status x2
        if: always()
        run: |
          sleep 100
          
          responseBody=$(curl -X GET \
          -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" \
          -H "Content-Type: application/json" \
          "https://testing.googleapis.com/v1/projects/${{ secrets.FIREBASE_PROJECT_ID }}/testMatrices/${{steps.tests.outputs.testMatrixId}}"/)
          
          echo "Test Matrix response body from get: $responseBody"
