name: Verify Pull-Request Description

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

permissions: read-all

jobs:
  verify:
    if: github.actor != 'dependabot[bot]'
    name: Verify Pull-Request Description
    runs-on: ubuntu-20.04

    steps:
      - name: Debug Workflow Context
        run: |
          echo "Actor is ${{ github.actor }}"
          echo "Event name is ${{ github.event_name }}"
          echo "Pull request title: ${{ github.event.pull_request.title }}"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            build-tools/
            .github/

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Verify PR
        shell: bash
        run: python "build-tools/verify-pr-description.py"
        env:
          TITLE: ${{ github.event.pull_request.title }}
          BODY: ${{ github.event.pull_request.body }}
